sudo: true

osx_image: xcode8.3

language: node_js

matrix:
  include:
    - os: osx
    - os: linux

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso
      - xvfb
      - libgnome-keyring-dev

install:
  - yarn
  - cd app && yarn && cd ..
  - export DISPLAY=':99.0'
  - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - node --version
  - yarn lint
  - yarn package
  - yarn test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn coveralls; fi
  - yarn test-e2e
  - yarn release
