os: unstable

branches:
  only:
    - master

environment:
  matrix:
    - nodejs_version: 8

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn config set ignore-engines true
  - set CI=true
  - yarn

test_script:
  - yarn lint
  - yarn package
  - yarn test
  - yarn test-e2e
  - yarn release
